Repository Financial-Times/origami-build-service, pull requests merged in 2020-12, with the labels that each got.

#391 Update website to use o-layout and add v3 endpoints for bundling
  .eslintrc.js
  .github/workflows/test.yml
  .gitignore
  .nvmrc
  README.md
  check_node_version.js
  data/navigation.json
  index.js
  lib/build-service.js
  lib/fileproxy.js
  lib/middleware/v3/bundleJavascript.js
  lib/middleware/v3/bundleSass.js
  lib/middleware/v3/createCssBundle.js
  lib/middleware/v3/createEntryFileJavaScript.js
  lib/middleware/v3/createEntryFileSass.js
  lib/middleware/v3/createJavaScriptBundle.js
  lib/middleware/v3/createPackageJsonFile.js
  lib/middleware/v3/installDependencies.js
  lib/middleware/v3/parseBrandParameter.js
  lib/middleware/v3/parseCallbackParameter.js
  lib/middleware/v3/parseModulesParameter.js
  lib/middleware/v3/parseSystemCodeParameter.js
  lib/moduleinstallation.js
  lib/primeNpmCache.js
  lib/registry.js
  lib/routes/v2/docs/api.js
  lib/routes/v2/docs/migration.js
  lib/routes/v2/index.js
  lib/routes/v3/bundles.js
  lib/routes/v3/docs/api.js
  lib/routes/v3/index.js
  package-lock.json
  package.json
  public/main.css
  test/integration/setup.test.js
  test/integration/v3-bundles-css.test.js
  test/integration/v3-bundles-js.test.js
  test/unit/lib/middleware/v3/bundleJavascript.test.js
  test/unit/lib/middleware/v3/bundleSass.test.js
  test/unit/lib/middleware/v3/createCssBundle.test.js
  test/unit/lib/middleware/v3/createEntryFileJavaScript.test.js
  test/unit/lib/middleware/v3/createEntryFileSass.test.js
  test/unit/lib/middleware/v3/createJavaScriptBundle.test.js
  test/unit/lib/middleware/v3/createPackageJsonFile.test.js
  test/unit/lib/middleware/v3/installDependencies.test.js
  test/unit/lib/middleware/v3/parseBrandParameters.test.js
  test/unit/lib/middleware/v3/parseCallbackParameters.test.js
  test/unit/lib/middleware/v3/parseModulesParameters.test.js
  test/unit/lib/middleware/v3/parseSystemCodeParameters.test.js
  test/unit/lib/registry.test.js
  test/unit/mock/registry.mock.js
  views/apiv2.html
  views/apiv3.html
  views/error.html
  views/index.html
  views/layouts/main.html
  views/migration.html
  views/partials/footer.html
  views/partials/header.html
  views/partials/navigation.html
Labels: current, service

#401 build(deps): npm audit fix
  package-lock.json
Labels: dependencies, security, service

#403 Wrap error messages in `pre` instead of `p`
  views/error.html
Labels: release:minor, service

#406 build(deps): npm audit fix
  package-lock.json
Labels: dependencies, security, service
