Repository Financial-Times/origami-build-service, pull requests merged in 2020-06, with the labels that each got.

#297 build(deps): npm audit fix
  package-lock.json
Labels: release:patch, service

#301 build(deps): npm audit fix
  package-lock.json
Labels: service

#302 Require latest node LTS (v12)
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
Labels: breaking, release:major, service

#303 build(deps): npm audit fix
  package-lock.json
Labels: release:patch, service

#305 make dependabot ignore snyk updates
  .dependabot/config.yml
Labels: service
