Repository Financial-Times/origami-build-service, pull requests merged in 2021-03, with the labels that each got.

#467 make v2 demo/html endpoint return pretty html output
  lib/middleware/outputDemo.js
Labels: service

#468 v3 -- rename modules and module query parameters to components and component
  lib/middleware/v3/buildDemo.js
  lib/middleware/v3/createCssBundle.js
  lib/middleware/v3/createEntryFileJavaScript.js
  lib/middleware/v3/createEntryFileSass.js
  lib/middleware/v3/createJavaScriptBundle.js
  lib/middleware/v3/createPackageJsonFile.js
  lib/middleware/v3/outputDemo.js
  lib/middleware/v3/outputFont.js
  lib/middleware/v3/parseComponentParameter.js
  lib/middleware/v3/parseComponentsParameter.js
  lib/middleware/v3/parseModuleParameter.js
  lib/middleware/v3/parseModulesParameter.js
  test/integration/v3-bundles-css.test.js
  test/integration/v3-bundles-js.test.js
  test/integration/v3-demos-html.test.js
  test/integration/v3-demos.test.js
  test/unit/lib/middleware/v3/createCssBundle.test.js
  test/unit/lib/middleware/v3/createEntryFileJavaScript.test.js
  test/unit/lib/middleware/v3/createJavaScriptBundle.test.js
  test/unit/lib/middleware/v3/parseComponentsParameter.test.js
  test/unit/lib/middleware/v3/parseModulesParameters.test.js
  views/apiv3.html
  views/migration.html
Labels: service

#469 Use prettier instead of pretty to get nicer output for demo html
  lib/middleware/outputDemo.js
  lib/middleware/v3/outputDemo.js
  package-lock.json
  package.json
  test/integration/v2-demos-html.test.js
  test/integration/v3-demos-html.test.js
  test/unit/lib/middleware/outputDemo.test.js
Labels: service

#471 build(deps): npm audit fix
  package-lock.json
Labels: dependencies, security, service

#473 Make build-service v3 css endpoint work for non o- prefixed components
  lib/middleware/v3/createEntryFileSass.js
Labels: service

#472 Only allows @financial-times namespaced components to be requested in v3
  lib/middleware/v3/createJavaScriptBundle.js
  lib/middleware/v3/parseComponentsParameter.js
  test/integration/v3-bundles-css.test.js
  test/integration/v3-bundles-js.test.js
  test/unit/lib/middleware/v3/createCssBundle.test.js
  test/unit/lib/middleware/v3/createJavaScriptBundle.test.js
  test/unit/lib/middleware/v3/parseComponentsParameter.test.js
Labels: current, service

#477 speed up integration tests by using the asserting the headers and body of a single response
  test/integration/about.test.js
  test/integration/bundles-css.test.js
  test/integration/bundles-js.test.js
  test/integration/demos.test.js
  test/integration/files.test.js
  test/integration/gtg.test.js
  test/integration/health.test.js
  test/integration/home.test.js
  test/integration/modules.test.js
  test/integration/robots.test.js
  test/integration/url-updater.test.js
  test/integration/v1-bundles-css.test.js
  test/integration/v1-bundles-js.test.js
  test/integration/v1-demos.test.js
  test/integration/v1-files.test.js
  test/integration/v1-modules.test.js
  test/integration/v1.test.js
  test/integration/v2-bundles-css.test.js
  test/integration/v2-bundles-js.test.js
  test/integration/v2-demos-html.test.js
  test/integration/v2-demos.test.js
  test/integration/v2-files.test.js
  test/integration/v2-modules.test.js
  test/integration/v2.test.js
  test/integration/v3-bundles-css.test.js
  test/integration/v3-bundles-js.test.js
  test/integration/v3-bundles-js.test.js.snap
  test/integration/v3-demos-html.test.js
  test/integration/v3-demos.test.js
  test/integration/v3-font.test.js
Labels: service

#476 only allow origami v2 components to be requested on the v3 api
  lib/middleware/v3/createCssBundle.js
  lib/middleware/v3/createJavaScriptBundle.js
  test/integration/v3-bundles-css.test.js
  test/integration/v3-bundles-js.test.js
  test/unit/lib/middleware/v3/createCssBundle.test.js
  test/unit/lib/middleware/v3/createJavaScriptBundle.test.js
Labels: service

#482 Add "o-three-sixty" to the v2 bundle allow list.
  lib/data/v2-module-allow-list.json
Labels: service

#486 use pull_request_target and not pull_request for the safe workflows
  .github/workflows/add-new-issues-and-pull-requests-to-origami-project-board.yml
  .github/workflows/apply-labels.yml
  .github/workflows/auto-approve.yml
  .github/workflows/sync-repo-labels.yml
Labels: service

#479 return an error response when attempting to build a demo whose html is invalid.
  lib/middleware/v3/outputDemo.js
  test/integration/v3-demos-html.test.js
Labels: current, service

#489 build(deps): npm audit fix
  package-lock.json
Labels: dependencies, security, service

#484 OBS v2: Allow the `latest` demos of a component to be returned
  lib/routes/v2/demos.js
  test/integration/v2-demos-html.test.js
  test/integration/v2-demos.test.js
Labels: service

#491 Add autoprefixer for css and use same browser config as origami-build-tools
  lib/middleware/v3/bundleSass.js
  package-lock.json
  package.json
  test/unit/lib/middleware/v3/bundleSass.test.js
Labels: service

#494 Return v2 demos with invalid html
  lib/middleware/outputDemo.js
  test/integration/v2-demos-html.test.js
Labels: service

#497 Restore the v3 "experimental" message
  views/apiv3.html
Labels: service

#496 Fix OBS v2 endpoints given component dependencies with invalid origam…
  lib/cssbundler.js
  lib/democompiler.js
  lib/fileproxy.js
  lib/jsbundler.js
  lib/modulemetadata.js
  test/integration/v2-bundles-css.test.js
  test/integration/v2-bundles-js.test.js
  test/integration/v2-demos-html.test.js
  test/integration/v2-demos.test.js
  test/integration/v2-files.test.js
Labels: service

#495 build(deps): npm audit fix
  package-lock.json
Labels: dependencies, security, service

#500 Report non-allowed shrink-wrapped modules requested in v2 bundles
  lib/middleware/reportDisallowedModules.js
Labels: service

#485 update v2 test to expect the "2.0" version string
  lib/middleware/v3/isOrigamiV2Component.js
  lib/url-updater/parse-modules-parameter.js
  test/integration/v2-bundles-css.test.js
  test/integration/v2-bundles-js.test.js
  test/integration/v2-demos-html.test.js
  test/integration/v2-demos.test.js
  test/integration/v2-files.test.js
  test/integration/v3-bundles-css.test.js
  test/integration/v3-bundles-js.test.js
  test/integration/v3-demos-html.test.js
  test/integration/v3-demos.test.js
  test/unit/lib/middleware/v3/createCssBundle.test.js
  test/unit/lib/middleware/v3/createJavaScriptBundle.test.js
  test/unit/lib/middleware/v3/outputDemo.test.js
  test/unit/lib/url-updater/evaluate-modules.test.js
  test/unit/lib/url-updater/parse-modules-parameter.test.js
  test/unit/lib/url-updater/update-url-for-results.test.js
Labels: service

#501 Error rather than report unexpected modules.
  lib/data/v2-module-allow-list.json
  lib/data/v2-shrinkwrap-module-allow-list.json
  lib/middleware/cleanModulesParameter.js
  lib/middleware/cleanShrinkwrapParameter.js
  lib/middleware/reportDisallowedModules.js
  lib/routes/v2/bundles.js
  test/integration/v2-bundles-css.test.js
  test/integration/v2-bundles-js.test.js
  test/integration/v2-modules.test.js
Labels: service
