Repository Financial-Times/origami-build-service, pull requests merged in 2021-02, with the labels that each got.

#435 Stop trying to add o-fonts-assets to the npm cache
  lib/primeNpmCache.js
Labels: service

#436 Make errors in v3 api be served as plain text and with nosniff enabled
  lib/middleware/v3/createCssBundle.js
  lib/middleware/v3/createJavaScriptBundle.js
  lib/middleware/v3/parseBrandParameter.js
  lib/middleware/v3/parseModulesParameter.js
  test/integration/v3-bundles-css.test.js
  test/integration/v3-bundles-js.test.js
  test/unit/lib/middleware/v3/createCssBundle.test.js
  test/unit/lib/middleware/v3/createJavaScriptBundle.test.js
  test/unit/lib/middleware/v3/parseBrandParameters.test.js
  test/unit/lib/middleware/v3/parseModulesParameters.test.js
Labels: service

#438 Return an error page if using the v2 api with an origami spec v2 component
  lib/cssbundler.js
  lib/democompiler.js
  lib/fileproxy.js
  lib/jsbundler.js
  lib/middleware/outputBundle.js
  lib/middleware/outputDemo.js
  lib/middleware/outputFile.js
  lib/moduleinstallation.js
  lib/modulemetadata.js
  test/integration/v2-bundles-css.test.js
  test/integration/v2-bundles-js.test.js
  test/integration/v2-demos.test.js
  test/integration/v2-files.test.js
  test/unit/lib/middleware/outputDemo.test.js
  test/unit/mock/moduleinstallation.mock.js
Labels: service

#437 Install `o-fonts-assets` with Github for the v3 files endpoint
  .github/workflows/test.yml
  README.md
  lib/middleware/v3/outputFont.js
Labels: service

#426 Add /v3/font api endpoint
  .github/workflows/test.yml
  README.md
  lib/middleware/v3/installDependencies.js
  lib/middleware/v3/outputFont.js
  lib/middleware/v3/parseFontFormatParameter.js
  lib/middleware/v3/parseFontNameParameter.js
  lib/middleware/v3/parseVersionParameter.js
  lib/routes/v3/font.js
  package-lock.json
  package.json
  test/integration/v3-bundles-css.test.js
  test/integration/v3-font.test.js
  test/unit/lib/middleware/v3/parseFontFormatParameter.test.js
  test/unit/lib/middleware/v3/parseFontNameParameter.test.js
  test/unit/lib/middleware/v3/parseVersionParameter.test.js
  views/apiv3.html
  views/migration.html
Labels: release:minor, service

#439 build(deps): npm audit fix
  package-lock.json
Labels: dependencies, security, service

#443 Restrict demo builds to valid semver releases (v2)
  lib/routes/v2/demos.js
  test/integration/v2-demos.test.js
  test/integration/v2-files.test.js
Labels: release:patch, service

#448 Remove cache control from post requests `url-updater`
  lib/routes/url-updater.js
Labels: service

#457 Report modules requested in v2 bundles which are not on an allow list
  lib/data/v2-module-allow-list.json
  lib/middleware/reportDisallowedModules.js
  lib/routes/v2/bundles.js
Labels: release:minor, service

#459 [Snyk] Security upgrade lodash from 4.17.20 to 4.17.21
  package-lock.json
  package.json
Labels: service

#462 simplify our dependabot auto-merge system
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
Labels: service
